### ISSUE TITLE
error from melpa

### ISSUE THREAD

**Issue by andreas-roehler** [purcell/flymake-python-pyflakes#14]
Got an error with 

GNU Emacs 25.1.50.1 (x86_64-suse-linux-gnu, GTK+ Version 3.16.7) of 2015-11-23

which seems to point here:

Debugger entered--Lisp error: (error "Error retrieving: https://melpa.org/packages/flymake-python-pyflakes-20131127.6.el \"incomprehensible buffer\"")
  signal(error ("Error retrieving: https://melpa.org/packages/flymake-python-pyflakes-20131127.6.el \"incomprehensible buffer\""))
  #[257 "p\306\216\3071\210

**Comment by purcell** [comment]
Works for me. Please retry. The pasted backtrace doesn't provide much info, so I have no way to reproduce this problem.

**Comment by andreas-roehler** [comment]
Changed the system meanwhile, let's forget it, thanks.
