### ISSUE TITLE
extra-arguments do not go to flake8

### ISSUE THREAD

**Issue by lxmonk** [purcell/flymake-python-pyflakes#15]
I'm using this setup in my .emac.d/personal.el

;; use flake8 in flymake-python-pyflakes
(require 'flymake-python-pyflakes)
(add-hook 'python-mode-hook 'flymake-python-pyflakes-load)
(setq flymake-python-pyflakes-executable "flake8")
(setq flymake-python-pyflakes-extra-arguments '("--max-line-length=100"
                                                "--max-complexity=10"))

I still get warning about lines that are less than 100 chars long.

**Comment by purcell** [comment]
Odd. I can't see why that would happen. Can you `(setq flymake-log-level 4)` to see what command is actually getting run?

**Comment by aviad** [comment]
my bad - it was flycheck with the errors. Now all that is left is getting the error message - all I get now is a curved line under the problem..

**Comment by purcell** [comment]
Aha, great! FWIW, I've personally switched over to `flycheck` entirely, and don't use any of my `flymake-*` packages.
