### ISSUE TITLE
Line length config ignored, tox.ini ignored

### ISSUE THREAD

**Issue by revmischa** [purcell/flymake-python-pyflakes#16]
I have various `[flake8]` settings in my project's `tox.ini` file that appear to have no effect when using flake8.

I tried setting `flycheck-flake8-maximum-line-length` but I still get warnings that lines are over 79 characters.

<img width="1516" alt="screen shot 2017-12-09 at 05 13 15" src="https://user-images.githubusercontent.com/245131/33785447-0ea75e6c-dca0-11e7-97fc-7212ebf8b006.png">

**Comment by purcell** [comment]
There is no such variable in this package. Probably you meant to report this against `flycheck` - see https://github.com/flycheck/flycheck/issues/872.
